### ISSUE TITLE
Order of articles on package site

### ISSUE THREAD

**Issue by sheridar** [rnabioco/djvdj#104]
* Currently articles are listed in alphabetical order in "Articles" menu on site
* Would be better if we could specify the order so more basic ones are listed first, e.g. data import

**Comment by jayhesselberth** [comment]
example:

https://github.com/r-lib/pkgdown/blob/5bb671b1a8bac8e926479868681936f7c9ee41b3/pkgdown/_pkgdown.yml#L30-L39
