### ISSUE TITLE
confusing `filter_paired` argument

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/djvdj#117]
In the README, you have:

```r
so <- import_vdj(
  input         = so,      # Seurat or SingleCellExperiment object
  vdj_dir       = paths,   # Cellranger output directories
  filter_paired = FALSE    # Only include clonotypes with paired chains
)
```

But I would expect that if you *only* want paired chains (i.e., you are filtering other things out) then you should set `filter_paired = TRUE`. Is the logic backwards? Or maybe the comment is inaccurate?

**Comment by sheridar** [comment]
'filter_paired = TRUE' will only include paired chains, so the comment is inaccurate
