### ISSUE TITLE
overlapping labels in circos plot

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/djvdj#118]
Labels overlap in: https://rnabioco.github.io/djvdj/articles/gene-usage.html#circos-plot

Maybe use this approach: https://jokergoo.github.io/circlize_book/book/high-level-genomic-functions.html#labels-1

**Comment by jayhesselberth** [comment]
more overlaps here: https://rnabioco.github.io/djvdj/articles/similarity.html#circos-plot

**Comment by sheridar** [comment]
The strategy described above doesn't seem to work for chordDiagram(), instead included argument to rotate labels 90 degrees (see #126)
