### ISSUE TITLE
Mutation frequencies

### ISSUE THREAD

**Issue by kwells4** [rnabioco/djvdj#132]
Currently mutation frequencies are being calculated based on the length of the regions that have mutations. For example, if mutations are seen in the V, D, and J region, the calculation is

```R
mut_freq = n_mutations / (v_length + j_length + d_length)
```

But if mutations are only seen in the V region, the calculation is

```R
mut_freq = n_mutations / (v_length)
```

Should be updated so that the denominator is always `(v_length + j_length + d_length)` no matter what mutations are seen. If no D gene is present, this will just b 0.

**Comment by sheridar** [comment]
Thanks @kwells4! #133
