### ISSUE TITLE
Differences in diversity analysis when using other packages

### ISSUE THREAD

**Issue by abedkurdi** [rnabioco/djvdj#142]
Hello there,

First, I would like to thank you for this great package, I have been looking for such tool a while ago!
Second, I was comparing the diversity plots, output from your package and output from `scRepertoire` R/Bioconductor package. 

I thought I would be able to reproduce, if not identical results, something very similar when using both packages. However, it was not the case 
![Screenshot from 2024-03-11 14-25-12](https://github.com/rnabioco/djvdj/assets/45813669/becee6bd-9c24-43c9-9af9-d7a43ac7ed27)

![Screenshot from 2024-03-11 14-25-51](https://github.com/rnabioco/djvdj/assets/45813669/dd4c7f07-5cc1-4a07-a8e4-c0b5df50b8c6)

I counted the number of unique clonotypes in both analyses and I got the exact same number for each hashtag.

Do you have any idea what could be happening here? I appreciate your help.

**Comment by sheridar** [comment]
Hi @abedkurdi, sorry about the delay, I'm looking into this

**Comment by abedkurdi** [comment]
Hello @sheridar 
The reason behind this is bootstrapping.

**Comment by sheridar** [comment]
This issue seems resolved, feel free to open a new issue if you have any other issues/questions
