### ISSUE TITLE
Reproducibility issues

### ISSUE THREAD

**Issue by Ahmedalaraby20** [rnabioco/djvdj#145]
Hey Rayn, 
So I ran 
```
run1 |> plot_diversity(data_col = "cdr3", cluster_col = "seurat_clusters",chain = "TRA" , downsample = T, method  = div_fns, alpha = 0.5, linetype = 2, color    = "black",n_boots = 150)
```
and each time I run it I get a slightly different output
![TCR1](https://github.com/rnabioco/djvdj/assets/37757151/96035cad-bc8a-4615-aad1-574a44b2a324)
![TCR2](https://github.com/rnabioco/djvdj/assets/37757151/aa27f10b-e567-42a2-a855-e98dca50fbaf)
![TCR3](https://github.com/rnabioco/djvdj/assets/37757151/9071889e-28f0-473f-a16d-4dd0a03b8258)

I usually have `set.seed("44")`
but it looks like it's not helping

The same happens when `downsample = F`
[djvdj.zip](https://github.com/rnabioco/djvdj/files/15284107/djvdj.zip)

**Comment by sheridar** [comment]
Hi @Ahmedalaraby20, I have not been able to reproduce this issue. Try running set.seed() before each time you run the command, this should ensure reproducible results
