### ISSUE TITLE
Add useful examples

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/djvdj#48]
Jotting these down for reference to add later

#### `filter_vdj()`

```r
#' @examples
#' # filter for cells with specific numbers of chains
#' filter_vdj(tiny_vdj, length(chains) == 3)

**Comment by sheridar** [comment]
* examples added with #87
* fix examples so they give more useful outputs for site

**Comment by jayhesselberth** [comment]
Spot check to identify long example outputs: https://rnabioco.github.io/djvdj/reference/summarize_vdj.html

**Comment by sheridar** [comment]
f0f8cfe194fa32b9450dd2957e013f9f707401a4
