### ISSUE TITLE
djvdj for SingleCellExperiment objects

### ISSUE THREAD

**Issue by friedue** [rnabioco/djvdj#60]
Hi guys,

thanks for the very useful selection of functions you've created for interacting with VDJ data! I've started to edit the functions so that they'll work with SingleCellExperiment objects, too: <https://github.com/friedue/SCEdjvdj> 

Feel free to link to it if someone comes asking; forks and contributions very welcome, of course.

Cheers,

Friederike

**Comment by sheridar** [comment]
Thanks Friederike! This is something I've thought about, but haven't gotten around to it. Be sure to let me know if you have any other suggestions

Ryan

**Comment by friedue** [comment]
We could aim for turning it into a Bioconductor package. Happy to chip in eventually, but not before end of March.

**Comment by jayhesselberth** [comment]
Support for SingleCellExperiment should probably be added via S3 dispatch
