### ISSUE TITLE
input for djvdj

### ISSUE THREAD

**Issue by ibseq** [rnabioco/djvdj#65]
hello, 
what output from cellranger can be used as input for djvdj to look at gene usage?
also, can this be customised...e.g. showing specific barcodes, rather than all those from cellranger?

thanks
ibseq

**Comment by sheridar** [comment]
Hi @ibseq, the `import_vdj` function uses the filtered_contig_annotations.csv file in the cellranger output directory to add the VDJ results to your Seurat object. Once you have added the VDJ data to the Seurat object, you can filter the object to exclude certain cell barcodes from the analysis. Filtering the Seurat object can be accomplished using `subset` or we also have a `filter_vdj` function that allows you to filter cells based on the VDJ data.

The tutorial and reference page have more information about these functions: https://rnabioco.github.io/djvdj
Let me know if you have any more questions or comments
