### ISSUE TITLE
Add data sets for readme vignette rendering

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/djvdj#75]

**Comment by jayhesselberth** [comment]
The pkgdown site build is broken because we shut down AWS

**Comment by sheridar** [comment]
* need better vignette using public data

**Comment by jayhesselberth** [comment]
I can't build the readme because these paths aren't available in the pacakge:

```r
paths <- c(
  KI_DN3_GE = "data/tcr/KI_DN3_TCR/outs",
  KI_DN4_GE = "data/tcr/KI_DN4_TCR/outs",
  WT_DN3_GE = "data/tcr/WT_DN3_TCR/outs",
  WT_DN4_GE = "data/tcr/WT_DN4_TCR/outs"
)
```

**Comment by sheridar** [comment]
The current dataset that's used in the README isn't published, so it's not included in the package. I'm going to update the README to use the same dataset shown in the vignettes on the package site.
