### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by Ahmedalaraby20** [rnabioco/djvdj#86]
Hey guys, 
I have been trying to install djvdj but unfortunately I always end up with this error.

> devtools::install_github("rnabioco/djvdj")

Error: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds

What am I doing wrong

**Comment by sheridar** [comment]
This error is not related to the package or repo. This is a connection timeout error for GitHub. I would try again later, or try to install a different package from GitHub and see if you have a similar issue

**Comment by sheridar** [comment]
@Ahmedalaraby20 I'm going to close this issue, please let me know if you have any other issues
