### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by seanken** [rnabioco/djvdj#88]
Really great tool! Maybe I missed it, but was hoping to cite this tool in a paper we are publishing and can't see if there is something to cite. Can always just cite the github directly, but was wondering if there is a paper, etc, I should cite instead? Thanks!

**Comment by sheridar** [comment]
Thanks @seanken! djvdj is still under development and has not been published yet, so you can cite github directly. The diversity/similarity metrics are calculated using the [abdiv](https://github.com/kylebittinger/abdiv) package. If you find our package useful feel free to star the repo, and please let me know if you have any suggestions for additional features that would be useful for your research
